alias fp="fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'"
alias v="nvim"
alias vim="nvim"
alias python="python3"
alias e="exit"
alias c="clear"
alias t="tmux"
alias dev="cd ~/Desktop/dev/"
alias school="cd ~/Desktop/school/"
alias npmdev="npm run dev -- --open"
alias ca="/bin/cat"
alias cat="bat --paging=never"
alias rm="trash"
alias please='sudo $(fc -ln -1)'
alias ,="cd"
alias ,,="cd .."

alias ls="exa --icons"
alias l="ls"
alias ll="ls -la"
alias la="ls -a"
alias sl="ls"

# GIT ALIAS
alias g="git"
alias gi="git init"
alias ga="git add"
alias gb="git branch"
alias gc="git commit --message"
alias gcl="git clone"
alias gp="git push"
alias gpl="git pull"
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
